// types/mockOrders.ts
export const mockOrders = [
  // ── Paris (4 commandes) ──
  {
    No: "101002",
    Sell_to_Customer_Name: "Adatum Corporation",
    Sell_to_City: "Paris",
    Sell_to_Address: "10 Rue de Rivoli",
    Sell_to_Post_Code: "75001",
    Sell_to_Country_Region_Code: "FR",
    Requested_Delivery_Date: "2026-02-14",
    volume: 15,
    capacity: 9000,
  },
  {
    No: "101003",
    Sell_to_Customer_Name: "School of Fine Art",
    Sell_to_City: "Paris",
    Sell_to_Address: "48 Rue Oberkampf",
    Sell_to_Post_Code: "75011",
    Sell_to_Country_Region_Code: "FR",
    Requested_Delivery_Date: "2026-02-14",
    volume: 10,
    capacity: 7000,
  },
  {
    No: "101004",
    Sell_to_Customer_Name: "Alpine Ski House",
    Sell_to_City: "Paris",
    Sell_to_Address: "112 Rue de Vaugirard",
    Sell_to_Post_Code: "75015",
    Sell_to_Country_Region_Code: "FR",
    Requested_Delivery_Date: "2026-02-16",
    volume: 9,
    capacity: 6000,
  },
  {
    No: "101005",
    Sell_to_Customer_Name: "Adatum Corporation",
    Sell_to_City: "Paris",
    Sell_to_Address: "5 Avenue des Champs-Élysées",
    Sell_to_Post_Code: "75008",
    Sell_to_Country_Region_Code: "FR",
    Requested_Delivery_Date: "2026-02-14",
    volume: 8,
    capacity: 5500,
  },

  // ── Lyon (3 commandes) ──
  {
    No: "101006",
    Sell_to_Customer_Name: "Adatum Corporation",
    Sell_to_City: "Lyon",
    Sell_to_Address: "2 Place Bellecour",
    Sell_to_Post_Code: "69002",
    Sell_to_Country_Region_Code: "FR",
    Requested_Delivery_Date: "2026-02-14",
    volume: 12,
    capacity: 8000,
  },
  {
    No: "101007",
    Sell_to_Customer_Name: "Adatum Corporation",
    Sell_to_City: "Lyon",
    Sell_to_Address: "18 Rue de la République",
    Sell_to_Post_Code: "69001",
    Sell_to_Country_Region_Code: "FR",
    Requested_Delivery_Date: "2026-02-14",
    volume: 11,
    capacity: 7500,
  },
  {
    No: "101008",
    Sell_to_Customer_Name: "Adatum Corporation",
    Sell_to_City: "Lyon",
    Sell_to_Address: "45 Quai Saint-Antoine",
    Sell_to_Post_Code: "69002",
    Sell_to_Country_Region_Code: "FR",
    Requested_Delivery_Date: "2026-02-16",
    volume: 7,
    capacity: 4500,
  },

  // ── Marseille (3 commandes) ──
  {
    No: "101009",
    Sell_to_Customer_Name: "Adatum Corporation",
    Sell_to_City: "Marseille",
    Sell_to_Address: "1 Quai du Port",
    Sell_to_Post_Code: "13002",
    Sell_to_Country_Region_Code: "FR",
    Requested_Delivery_Date: "2026-02-16",
    volume: 14,
    capacity: 9000,
  },
  {
    No: "101011",
    Sell_to_Customer_Name: "Adatum Corporation",
    Sell_to_City: "Marseille",
    Sell_to_Address: "20 La Canebière",
    Sell_to_Post_Code: "13001",
    Sell_to_Country_Region_Code: "FR",
    Requested_Delivery_Date: "2026-02-16",
    volume: 10,
    capacity: 7000,
  },
  {
    No: "101012",
    Sell_to_Customer_Name: "Trey Research",
    Sell_to_City: "Marseille",
    Sell_to_Address: "8 Boulevard Longchamp",
    Sell_to_Post_Code: "13001",
    Sell_to_Country_Region_Code: "FR",
    Requested_Delivery_Date: "2026-02-14",
    volume: 13,
    capacity: 8500,
  },

  // ── Toulouse (3 commandes) ──
  {
    No: "101013",
    Sell_to_Customer_Name: "Adatum Corporation",
    Sell_to_City: "Toulouse",
    Sell_to_Address: "1 Place du Capitole",
    Sell_to_Post_Code: "31000",
    Sell_to_Country_Region_Code: "FR",
    Requested_Delivery_Date: "2026-02-14",
    volume: 11,
    capacity: 7500,
  },
  {
    No: "101014",
    Sell_to_Customer_Name: "School of Fine Art",
    Sell_to_City: "Toulouse",
    Sell_to_Address: "30 Allées Jean Jaurès",
    Sell_to_Post_Code: "31000",
    Sell_to_Country_Region_Code: "FR",
    Requested_Delivery_Date: "2026-02-14",
    volume: 8,
    capacity: 5000,
  },
  {
    No: "101015",
    Sell_to_Customer_Name: "School of Fine Art",
    Sell_to_City: "Toulouse",
    Sell_to_Address: "15 Rue Alsace-Lorraine",
    Sell_to_Post_Code: "31000",
    Sell_to_Country_Region_Code: "FR",
    Requested_Delivery_Date: "2026-02-16",
    volume: 13,
    capacity: 8500,
  },

  // ── Nice (3 commandes) ──
  {
    No: "101016",
    Sell_to_Customer_Name: "Alpine Ski House",
    Sell_to_City: "Nice",
    Sell_to_Address: "7 Promenade des Anglais",
    Sell_to_Post_Code: "06000",
    Sell_to_Country_Region_Code: "FR",
    Requested_Delivery_Date: "2026-02-14",
    volume: 9,
    capacity: 6000,
  },
  {
    No: "101017",
    Sell_to_Customer_Name: "Trey Research",
    Sell_to_City: "Nice",
    Sell_to_Address: "12 Avenue Jean Médecin",
    Sell_to_Post_Code: "06000",
    Sell_to_Country_Region_Code: "FR",
    Requested_Delivery_Date: "2026-02-16",
    volume: 14,
    capacity: 9500,
  },
  {
    No: "101018",
    Sell_to_Customer_Name: "Trey Research",
    Sell_to_City: "Nice",
    Sell_to_Address: "3 Rue Masséna",
    Sell_to_Post_Code: "06000",
    Sell_to_Country_Region_Code: "FR",
    Requested_Delivery_Date: "2026-02-14",
    volume: 6,
    capacity: 4000,
  },

  // ── Bordeaux (3 commandes) ──
  {
    No: "101019",
    Sell_to_Customer_Name: "Alpine Ski House",
    Sell_to_City: "Bordeaux",
    Sell_to_Address: "10 Place de la Bourse",
    Sell_to_Post_Code: "33000",
    Sell_to_Country_Region_Code: "FR",
    Requested_Delivery_Date: "2026-02-14",
    volume: 16,
    capacity: 10000,
  },
  {
    No: "101020",
    Sell_to_Customer_Name: "Adatum Corporation",
    Sell_to_City: "Bordeaux",
    Sell_to_Address: "55 Rue Sainte-Catherine",
    Sell_to_Post_Code: "33000",
    Sell_to_Country_Region_Code: "FR",
    Requested_Delivery_Date: "2026-02-16",
    volume: 7,
    capacity: 4500,
  },
  {
    No: "101021",
    Sell_to_Customer_Name: "Relecloud",
    Sell_to_City: "Bordeaux",
    Sell_to_Address: "22 Quai des Chartrons",
    Sell_to_Post_Code: "33000",
    Sell_to_Country_Region_Code: "FR",
    Requested_Delivery_Date: "2026-02-14",
    volume: 12,
    capacity: 7800,
  },

  // ── Lille (3 commandes) ──
  {
    No: "101022",
    Sell_to_Customer_Name: "Relecloud",
    Sell_to_City: "Lille",
    Sell_to_Address: "2 Place du Général de Gaulle",
    Sell_to_Post_Code: "59000",
    Sell_to_Country_Region_Code: "FR",
    Requested_Delivery_Date: "2026-02-14",
    volume: 10,
    capacity: 6500,
  },
  {
    No: "101023",
    Sell_to_Customer_Name: "Trey Research",
    Sell_to_City: "Lille",
    Sell_to_Address: "40 Rue de Béthune",
    Sell_to_Post_Code: "59800",
    Sell_to_Country_Region_Code: "FR",
    Requested_Delivery_Date: "2026-02-16",
    volume: 8,
    capacity: 5500,
  },
  {
    No: "101024",
    Sell_to_Customer_Name: "Adatum Corporation",
    Sell_to_City: "Lille",
    Sell_to_Address: "15 Boulevard de la Liberté",
    Sell_to_Post_Code: "59000",
    Sell_to_Country_Region_Code: "FR",
    Requested_Delivery_Date: "2026-02-14",
    volume: 11,
    capacity: 7200,
  },

  // ── Strasbourg (2 commandes) ──
  {
    No: "101025",
    Sell_to_Customer_Name: "Alpine Ski House",
    Sell_to_City: "Strasbourg",
    Sell_to_Address: "5 Place Kléber",
    Sell_to_Post_Code: "67000",
    Sell_to_Country_Region_Code: "FR",
    Requested_Delivery_Date: "2026-02-14",
    volume: 12,
    capacity: 8000,
  },
  {
    No: "101026",
    Sell_to_Customer_Name: "School of Fine Art",
    Sell_to_City: "Strasbourg",
    Sell_to_Address: "18 Rue du Vieux-Marché-aux-Poissons",
    Sell_to_Post_Code: "67000",
    Sell_to_Country_Region_Code: "FR",
    Requested_Delivery_Date: "2026-02-16",
    volume: 9,
    capacity: 6000,
  },

  // ── Nantes (2 commandes) ──
  {
    No: "101027",
    Sell_to_Customer_Name: "Trey Research",
    Sell_to_City: "Nantes",
    Sell_to_Address: "1 Place Royale",
    Sell_to_Post_Code: "44000",
    Sell_to_Country_Region_Code: "FR",
    Requested_Delivery_Date: "2026-02-14",
    volume: 15,
    capacity: 9500,
  },
  {
    No: "101028",
    Sell_to_Customer_Name: "Relecloud",
    Sell_to_City: "Nantes",
    Sell_to_Address: "8 Cours des 50 Otages",
    Sell_to_Post_Code: "44000",
    Sell_to_Country_Region_Code: "FR",
    Requested_Delivery_Date: "2026-02-16",
    volume: 10,
    capacity: 6500,
  },
];
